version: '3.8'

services:
  agro_db:
    image: mysql:8.0
    container_name: agro_mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: agro_telemetria
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d 

  agro_etl:
    # Em vez de 'build: ./ETL', você puxa direto do Docker Hub
    image: seu_usuario_dockerhub/agro-etl:latest
    container_name: agro_etl_container
    restart: always
    depends_on:
      - agro_db
    environment:
      - DB_HOST=agro_db
      - DB_USER=root
      - DB_PASSWORD=root_password_aqui
      - DB_NAME=agro_telemetria
      - MQTT_BROKER=broker.hivemq.com
      - MQTT_PORT=1883
      - MQTT_TOPIC=kensley/fazenda/soja/telemetria

volumes:
  db_data: